# Generated by Django 3.1.2 on 2020-10-07 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_designation_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=300)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.designation')),
            ],
        ),
    ]
