# Generated by Django 3.1.2 on 2020-10-07 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201007_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('measure_unit', models.CharField(max_length=15, null=True)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productGroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.productgroup'),
            preserve_default=False,
        ),
    ]
