# Generated by Django 3.1.2 on 2020-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productparameter_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
