# Generated by Django 3.1.2 on 2020-10-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201007_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.designation', verbose_name='Назначение'),
        ),
    ]
