# Generated by Django 3.1.2 on 2020-10-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20201007_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
