# Generated by Django 3.1.2 on 2020-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='measure_unit',
            field=models.CharField(max_length=15, null=True, verbose_name='Еденица измерения'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название свойства'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='value',
            field=models.TextField(max_length=500, verbose_name='Значение'),
        ),
    ]
