# Generated by Django 3.1.2 on 2020-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20201009_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Еденица измерения'),
        ),
    ]
